### ISSUE TITLE
Ich werde nicht bei den Contributors angezeigt.

### ISSUE THREAD

**Issue by jdiemke** [marcolindner/dashboard#33]
Hallo Marco,

was läuft da schief?

https://github.com/marcolindner/dashboard/graphs/contributors

VG
Johannes

**Comment by jdiemke** [comment]
Laut Statistik habe ich eine Zeile Code geändert. Verstehe ich nicht ;)

**Comment by marcolindner** [comment]
Steht da doch "Contributions to develop" ohne Merge Commits.
