### ISSUE TITLE
Adjust widget update mechanism

### ISSUE THREAD

**Issue by db81eve** [marcolindner/dashboard#34]
- Die jetzige Implementierung hat eine leichte "Schwäche" im Umgang mit asynchronen "Datenhol-Requests"
=> Entkoppeln von "Daten im Widget vorbereiten" und "Daten zur Anzeige holen"

**Comment by jdiemke** [comment]
Ich glaube, dass eine "richtige" Entkopplung nicht notwendig ist, da ein Update der Widgets auf Client-Seite nicht häufiger als ein Update auf Server-Seite stattfinden muss.

Sprich es sollte austreichen, wenn die Widgets auf Server-Seite eine Neuberechnung in den definierten Update Intervallen antriggern und das Holen des Updates dann asynkron passiert. Sobald das Update im Server eingetroffen ist kann dieser das update in einer Zustandsvariable speichern und ein UpdateRequest an die Widgets auf Client-Seite senden. Wird jetzt noch bei
 einem initialen Connect eines Dashbards dieser Zustand direkt als UpdateRequest an ein Client-Widget gesendet, dann sind die Widgets auf Client-Seiten immer aktuell. Es muss nur eine Fallunterscheidung beim erzeugen eiens neuen Widgets auf Server-Seite stattfinden: Wird das widget neu erzeugt, dann muss das update einmal initial angetriggert werden bevor das setIntervall aufgerufen wird. Ansonsten existierte das Widget schon und es muss nur ein UpdateRequest an das Client-Wdiget mit den bereits berechneten Daten im Zustand des Server-Widgets gesendet werden.

**Comment by marcolindner** [comment]
Wir sollen möglichst zeitnah den Mongo Support integrieren. Dort gibt es die Möglichkeit auf Veränderungen der Datensätze zu lauschen und gezielt die Clientwidgets zu informieren. Das wäre die einfachste Möglichkeit der Entkoppelung.

**Comment by jdiemke** [comment]
Ich schlage vor, das ganze als MVC aufzufassen. Das Widget auf Server-Seite ist der Controller und das Modell. Die Update-Methode des Widgets auf Server-Seite ist im Prinzip der Controller, der "irgendwie" Daten erzeugt (bspw. durch ein REST Call auf eine externe API) die dann in einem Modell (interne Variable im Server-Widget analog zu der Implementierung von Denny) gespeichert werden. Ich schlage vor ein Update der interne Variable über eine spezielle setModel()- bzw. updateModel()-Methode durchzuführen. Das ermöglicht es dem AbstractWidget ein Modell-Update zu erkennen. Weiterhin halte ich es für sinnvoll die Client-Widgets als Listener/Observer des Modells des Server-Widgets aufzufassen. Dann müssen alle Client-Widgets nur noch auf ein Modell-Update des entsprechenden Server-Widgets lauschen.

In wie weit MongoDB uns behilflich sein kann ist mir noch nicht klar, da ich bisher keinen Grund erkenne wieso die die Widget Modelle in der DB persistiert werden sollten.

Ich schlage vor, dass wir das ganze in einem Termin besprechen.

VG
Johannes
